using ChasBWare.SpotLight.Domain.Enums;
using SpotifyAPI.Web;

namespace ChasBWare.SpotLight.Spotify.Interfaces
{
    public interface ISpotyConnectionSession
    {  
        /// <summary>
        /// unique app id from spotify
        /// </summary>
        public string ClientId { get; set; }

        /// <summary>
        /// unique id created for me by spotify
        /// </summary>
        public string ClientSecret { get; set; } 

        /// <summary>
        /// port used by callback during call to spotify
        /// authentication page
        /// </summary>
        public int RedirectPort { get; set; }

        /// <summary>
        /// address used by callback during call to spotify
        /// authentication page
        /// </summary>
        public string RedirectUrl { get; set; }

        /// <summary>
        /// OAuth token, will be stored in SecureStoreage so is not visible.
        /// (see: InstallViewModel for how it is loaded at moment)
        /// </summary>
        string? AccessToken { get; }

        /// <summary>
        /// OAuth refresh token generated by spotify
        /// </summary>
        string? RefreshToken { get; }

        SpotifyClient GetClient();
        ICollection<string> GetScopes();
        ConnectionStatus RestoreTokens();
        ConnectionStatus UpdateTokens(string accessToken, string refreshToken);
        ConnectionStatus UpdateToken(string accessToken);
    }
}